<?php

/**
 * Colombia places
 *
 * @version  1.1.24
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['CO'] = array(
    '63' => array(
        'CIRCASIA (QDIO)',
        'LA TEBAIDA (QDIO)',
        'MONTENEGRO (QDIO)',
        'PIJAO (QDIO)',
        'SALENTO (QDIO)',
        'QUIMBAYA (QDIO)',
        'ARMENIA (QDIO)',
        'CALARCA (QDIO)',
        'BARCELONA (QDIO)',
        'CORDOBA (QDIO)',
        'BUENAVISTA (QDIO)',
        'FILANDIA (QDIO)',
        'GENOVA (QDIO)',
    ),
    '27' => array(
        'SAN JOSE DEL PALMAR (CHOCO)',
        'ANIMAS (CHOCO)',
        'BAHIA SOLANO MUTIS (CHOCO)',
        'BOJAYA (CHOCO)',
        'TADO (CHOCO)',
        'LLORO (CHOCO)',
        'RIOSUCIO (CHOCO)',
        'NUQUI (CHOCO)',
        'ACANDI (CHOCO)',
        'SIPI (CHOCO)',
        'ALTO BAUDO (CHOCO)',
        'EL CARMEN DE ATRATO (CHOCO)',
        'CAPURGANA (CHOCO)',
        'QUIBDO (CHOCO)',
        'JURADO (CHOCO)',
        'ANDAGOYA (CHOCO)',
        'SANTA MARIA DEL DARIEN (CHOCO)',
        'CONDOTO (CHOCO)',
        'GUARATO (CHOCO)',
        'UNGUIA (CHOCO)',
        'TUTUNENDO (CHOCO)',
        'ISTMINA (CHOCO)',
        'YUTO (CHOCO)',
        'BAJO BAUDO PIZARRO (CHOCO)',
        'NOVITA (CHOCO)',
        'CERTEGUI (CHOCO)',
    ),
    '76' => array(
        'SAN PEDRO (VALLE)',
        'AMAIME (VALLE)',
        'ALCALA (VALLE)',
        'CANDELARIA (VALLE)',
        'VILLA GORGONA (VALLE)',
        'LOBO GUERRERO (VALLE)',
        'GUACARI (VALLE)',
        'FLORIDA (VALLE)',
        'RIO FRIO (VALLE)',
        'EL CAIRO (VALLE)',
        'TULUA (VALLE)',
        'BUGA (VALLE)',
        'ANDALUCIA (VALLE)',
        'BUGA LA GRANDE (VALLE)',
        'EL QUEREMAL (VALLE)',
        'ANSERMA NUEVO (VALLE)',
        'BUENAVENTURA (VALLE)',
        'FENICIA (VALLE)',
        'SEVILLA (VALLE)',
        'COSTA RICA (VALLE)',
        'DARIEN (VALLE)',
        'RESTREPO (VALLE)',
        'LA CUMBRE (VALLE)',
        'LA URIBE (VALLE)',
        'LA UNION (VALLE)',
        'DAGUA (VALLE)',
        'ROLDANILLO (VALLE)',
        'TORO (VALLE)',
        'ULLOA (VALLE)',
        'OBANDO (VALLE)',
        'ZARZAL (VALLE)',
        'BOLIVAR (VALLE)',
        'VERSALLES (VALLE)',
        'PUENTE TIERRA (VALLE)',
        'EL AGUILA (VALLE)',
        'CALI (VALLE)',
        'EL CARMELO (VALLE)',
        'PRADERA (VALLE)',
        'EL CERRITO (VALLE)',
        'EL PLACER (VALLE)',
        'SONSO (VALLE)',
        'YUMBO (VALLE)',
        'VIJES (VALLE)',
        'SANTA ELENA (VALLE)',
        'ARGELIA (VALLE)',
        'LA VICTORIA (VALLE)',
        'PRESIDENTE (VALLE)',
        'LA PAILA (VALLE)',
        'PALMIRA (VALLE)',
        'HOLGUIN (VALLE)',
        'SALONICA LA MARINA (VALLE)',
        'EL DOVIO (VALLE)',
        'CAICEDONIA (VALLE)',
        'CARTAGO (VALLE)',
        'GINEBRA (VALLE)',
        'REMOLINO (VALLE)',
        'CISNEROS (VALLE)',
        'ROZO (VALLE)',
        'TRUJILLO (VALLE)',
        'YOTOCO (VALLE)',
        'JAMUNDI (VALLE)',
    ),
    '99' => array(
        'LA PRIMAVERA (VICH)',
        'SANTA ROSALIA (VICH)',
        'PUERTO CARREÑO (VICH)',
        'CUMARIBO (VICH)',
    ),
    '05' => array(
        'SANTA ROSA DE OSOS (ANT)',
        'PUERTO BELGICA (ANT)',
        'ZUNGO CARRETERA (ANT)',
        'ARGELIA (ANT)',
        'CIUDAD BOLIVAR (ANT)',
        'YONDO CASABE (ANT)',
        'LA CEJA (ANT)',
        'CARACOLI (ANT)',
        'CAROLINA DEL PRINCIPE (ANT)',
        'SABANETA (ANT)',
        'GIRALDO (ANT)',
        'SAN MIGUEL (ANT)',
        'HELICONIA (ANT)',
        'HISPANIA (ANT)',
        'ARMENIA MANTEQUILLA (ANT)',
        'ANDES (ANT)',
        'ANORI (ANT)',
        'ITUANGO (ANT)',
        'ABRIAQUI (ANT)',
        'BETULIA (ANT)',
        'JERICO (ANT)',
        'JARDIN SUROESTE (ANT)',
        'OLAYA (ANT)',
        'COCORNA (ANT)',
        'LA PINTADA (ANT)',
        'ANGELOPOLIS (ANT)',
        'JARDIN CACERES (ANT)',
        'CONCORDIA (ANT)',
        'FREDONIA (ANT)',
        'CAREPA (ANT)',
        'CHIGORODO (ANT)',
        'CISNEROS (ANT)',
        'ABEJORRAL (ANT)',
        'BETANIA (ANT)',
        'DABEIBA (ANT)',
        'LIBORINA (ANT)',
        'LA ESTRELLA (ANT)',
        'LLANADAS (ANT)',
        'SONSON (ANT)',
        'NECOCLI (ANT)',
        'MUTATA (ANT)',
        'BELMIRA (ANT)',
        'CONCEPCION (ANT)',
        'SAN ANDRES DE CUERQUIA (ANT)',
        'PALMITAS (ANT)',
        'SABANALARGA (ANT)',
        'SAN JERONIMO (ANT)',
        'PUERTO BERRIO (ANT)',
        'PUERTO NARE (ANT)',
        'SAN CARLOS (ANT)',
        'PUERTO TRIUNFO (ANT)',
        'LA SIERRA (ANT)',
        'REMEDIOS (ANT)',
        'EBEJICO (ANT)',
        'LA CRUZADA (ANT)',
        'SANTA ISABELL (ANT)',
        'SAN JUAN DE URABA (ANT)',
        'SALGAR (ANT)',
        'SAN LUIS (ANT)',
        'GRANADA (ANT)',
        'GOMEZ PLATA (ANT)',
        'NECHI (ANT)',
        'ANZA (ANT)',
        'BURITICA (ANT)',
        'TARAZA (ANT)',
        'LLANOS DE CUIVA (ANT)',
        'SEVILLA (ANT)',
        'BRICEÑO (ANT)',
        'SAN JOSE DEL NUS (ANT)',
        'SAN RAFAEL (ANT)',
        'BOLOMBOLO (ANT)',
        'CAÑASGORDAS (ANT)',
        'ARBOLETES (ANT)',
        'SANTO DOMINGO (ANT)',
        'SANTIAGO (ANT)',
        'EL DOCE (ANT)',
        'AMAGA (ANT)',
        'EL BAGRE (ANT)',
        'DORADAL (ANT)',
        'EL CARMEN DE VIBORAL (ANT)',
        'MURINDO (ANT)',
        'COPACABANA (ANT)',
        'CALDAS (ANT)',
        'GIRARDOTA (ANT)',
        'MARINILLA (ANT)',
        'SAN ANTONIO DE PRADO (ANT)',
        'BELLO (ANT)',
        'GUARNE (ANT)',
        'EL TRES (ANT)',
        'URAMITA (ANT)',
        'URRAO (ANT)',
        'VALDIVIA (ANT)',
        'ANGOSTURA (ANT)',
        'CACERES (ANT)',
        'SAN PEDRO DE URABA (ANT)',
        'TOLEDO (ANT)',
        'TURBO (ANT)',
        'TARSO (ANT)',
        'TITIRIBI (ANT)',
        'CURRULAO (ANT)',
        'SOPETRAN (ANT)',
        'TAMESIS (ANT)',
        'SEGOVIA (ANT)',
        'NARIÑO (ANT)',
        'NUEVA COLONIA (ANT)',
        'BARBOSA (ANT)',
        'APARTADO (ANT)',
        'CAUCASIA (ANT)',
        'ENTRERRIOS (ANT)',
        'SAN PEDRO DE LOS MILAGROS (ANT)',
        'EL SANTUARIO (ANT)',
        'MEDELLIN (ANT)',
        'DONMATIAS (ANT)',
        'SAN FRANCISCO (ANT)',
        'ALTAMIRA (ANT)',
        'SAN JOSE DE LA MONTAÑA (ANT)',
        'SANTA BARBARA (ANT)',
        'VERSALLES (ANT)',
        'PEQUE (ANT)',
        'YALI (ANT)',
        'ZARAGOZA (ANT)',
        'PUERTO VALDIVIA (ANT)',
        'ITAGUI (ANT)',
        'EL TIGRE (ANT)',
        'VEGACHI (ANT)',
        'VALPARAISO (ANT)',
        'PALERMO (ANT)',
        'VENECIA (ANT)',
        'SAN ROQUE (ANT)',
        'SAN VICENTE (ANT)',
        'ENVIGADO (ANT)',
        'CARAMANTA (ANT)',
        'SANTA ELENA (ANT)',
        'GUATAPE (ANT)',
        'LA UNION (ANT)',
        'AMALFI (ANT)',
        'RIONEGRO (ANT)',
        'ALEJANDRIA (ANT)',
        'RETIRO (ANT)',
        'LA TABLAZA (ANT)',
        'EL PEÑOL (ANT)',
        'BELEN DE BAJIRA (CHOCO)',
        'PUEBLORRICO (ANT)',
        'SANTA FE DE ANTIOQUIA (ANT)',
        'GUADALUPE (ANT)',
        'FRONTINO (ANT)',
        'CAICEDO (ANT)',
        'CAMPAMENTO (ANT)',
        'MACEO (ANT)',
        'YARUMAL (ANT)',
        'MONTEBELLO (ANT)',
        'YOLOMBO (ANT)',
    ),
    '15' => array(
        'BRICEÑO (BOY)',
        'SAN EDUARDO (BOY)',
        'PANTANO DE VARGAS (BOY)',
        'PUERTO BOYACA (BOY)',
        'CHIQUINQUIRA (BOY)',
        'NOBSA (BOY)',
        'TUNJA (BOY)',
        'EL ESPINO (BOY)',
        'EL COCUY (BOY)',
        'FIRAVITOBA (BOY)',
        'COPER (BOY)',
        'TOTA (BOY)',
        'TUNUNGUA (BOY)',
        'CUITIVA (BOY)',
        'BUENAVISTA (BOY)',
        'BELEN (BOY)',
        'BETEITIVA (BOY)',
        'CHITARAQUE (BOY)',
        'AQUITANIA (BOY)',
        'CHINAVITA (BOY)',
        'CHISCAS (BOY)',
        'SOCOTA (BOY)',
        'COVARACHIA (BOY)',
        'ARCABUCO (BOY)',
        'TASCO (BOY)',
        'LABRANZAGRANDE (BOY)',
        'SUSACON (BOY)',
        'TOGUI (BOY)',
        'SORA (BOY)',
        'SIACHOQUE (BOY)',
        'SOATA (BOY)',
        'SOGAMOSO (BOY)',
        'TIBASOSA (BOY)',
        'SOCHA (BOY)',
        'SORACA (BOY)',
        'SOTAQUIRÁ (BOY)',
        'SUTAMARCHAN (BOY)',
        'TIBANA (BOY)',
        'TINJACA (BOY)',
        'SAN JOSE DE PARE (BOY)',
        'SANTANA (BOY)',
        'PUERTO SERVIEZ (BOY)',
        'MIRAFLORES (BOY)',
        'LA UVITA (BOY)',
        'MACANAL (BOY)',
        'MARIPI (BOY)',
        'MOTAVITA (BOY)',
        'MUZO (BOY)',
        'OICATA (BOY)',
        'PAIPA (BOY)',
        'RAMIRIQUI (BOY)',
        'PAZ DE RIO (BOY)',
        'COSCUEZ (BOY)',
        'RAQUIRA (BOY)',
        'RONDON (BOY)',
        'SABOYA (BOY)',
        'SAMACA (BOY)',
        'SAN MATEO (BOY)',
        'SAN MIGUEL DE SEMA (BOY)',
        'SAN PABLO DE BORBUR (BOY)',
        'SANTA SOFIA (BOY)',
        'SANTA ROSA DE VITERBO (BOY)',
        'TENZA (BOY)',
        'GUACAMAYAS (BOY)',
        'IZA (BOY)',
        'GARAGOA (BOY)',
        'CUBARA (BOY)',
        'GUAYATA (BOY)',
        'CHIQUIZA (BOY)',
        'ALMEIDA (BOY)',
        'LA CAPILLA (BOY)',
        'DUITAMA (BOY)',
        'CHIVOR (BOY)',
        'CIÉNEGA (BOY)',
        'COMBITA (BOY)',
        'CORRALES (BOY)',
        'CUCAITA (BOY)',
        'GUICÁN (BOY)',
        'JENESANO (BOY)',
        'GUATEQUE (BOY)',
        'SUTATENZA (BOY)',
        'PESCA (BOY)',
        'CAMPOHERMOSO (BOY)',
        'CHIVATA (BOY)',
        'GACHANTIVA (BOY)',
        'GAMEZA (BOY)',
        'FLORESTA (BOY)',
        'PANQUEBA (BOY)',
        'PAUNA (BOY)',
        'QUIPAMA (BOY)',
        'SOMONDOCO (BOY)',
        'NUEVO COLON (BOY)',
        'SANTA MARIA (BOY)',
        'NARIÑO (BOY)',
        'BOAVITA (BOY)',
        'BOYACA (BOY)',
        'BUSBANZA (BOY)',
        'CALDAS (BOY)',
        'CERINZA (BOY)',
        'BERBEO (BOY)',
        'OTANCHE (BOY)',
        'PACHAVITA (BOY)',
        'VILLA DE LEYVA (BOY)',
        'BELENCITO (BOY)',
        'MONIQUIRA (BOY)',
        'PAEZ (BOY)',
        'PAJARITO (BOY)',
        'SACHICA (BOY)',
        'SAN LUIS DE GACENO (BOY)',
        'TIPACOQUE (BOY)',
        'TOCA (BOY)',
        'TOPAGA (BOY)',
        'VENTAQUEMADA (BOY)',
        'TUTA (BOY)',
        'UMBITA (BOY)',
        'TURMEQUE (BOY)',
        'TUTAZA (BOY)',
        'VIRACACHA (BOY)',
        'ZETAQUIRA (BOY)',
        'PUENTE BOYACA (BOY)',
        'SANTA BARBARA (BOY)',
        'LA VICTORIA (BOY)',
        'SATIVANORTE (BOY)',
        'SATIVASUR (BOY)',
        'MONGUI (BOY)',
        'MONGUA (BOY)',
        'CHITA (BOY)',
        'JERICÓ (BOY)',
    ),
    '18' => array(
        'ALBANIA (CAQ)',
        'LA MONTAÑITA (CAQ)',
        'SOLITA (CAQ)',
        'BELEN DE LOS ANDAQUIES (CAQ)',
        'CARTAGENA DEL CHAIRA (CAQ)',
        'CURILLO (CAQ)',
        'EL DONCELLO (CAQ)',
        'EL PAUJIL (CAQ)',
        'VALPARAISO (CAQ)',
        'RIONEGRO (CAQ)',
        'MORELIA (CAQ)',
        'SAN VICENTE DEL CAGUAN (CAQ)',
        'FLORENCIA (CAQ)',
        'PUERTO RICO (CAQ)',
        'SAN JOSE DEL FRAGUA (CAQ)',
    ),
    '95' => array(
        'SAN JOSE DEL GUAVIARE (G/VIARE)',
    ),
    '25' => array(
        'BOGOTA (C/MARCA)',
        'FUSAGASUGA (C/MARCA)',
        'FUQUENE (C/MARCA)',
        'FOMEQUE (C/MARCA)',
        'CAPELLANIA (C/MARCA)',
        'VILLAGOMEZ (C/MARCA)',
        'TIBIRITA (C/MARCA)',
        'TENA (C/MARCA)',
        'CARTAGENA (C/MARCA)',
        'SAN BERNARDO (C/MARCA)',
        'VIANI (C/MARCA)',
        'SUBACHOQUE (C/MARCA)',
        'TIBACUY (C/MARCA)',
        'TOCAIMA (C/MARCA)',
        'LA PUNTA (C/MARCA)',
        'SASAIMA (C/MARCA)',
        'SIMIJACA (C/MARCA)',
        'UBALA (C/MARCA)',
        'UBATE (C/MARCA)',
        'SUESCA (C/MARCA)',
        'CAMBAO (C/MARCA)',
        'LA CALERA (C/MARCA)',
        'COTA (C/MARCA)',
        'SILVANIA (C/MARCA)',
        'GUATAVITA (C/MARCA)',
        'UBAQUE (C/MARCA)',
        'ZIPACON (C/MARCA)',
        'RICAURTE (C/MARCA)',
        'EL CHARQUITO (C/MARCA)',
        'QUEBRADANEGRA (C/MARCA)',
        'PUENTE QUETAME (C/MARCA)',
        'SUTATAUSA (C/MARCA)',
        'VILLAPINZON (C/MARCA)',
        'VERGARA (C/MARCA)',
        'MOSQUERA (C/MARCA)',
        'SESQUILE (C/MARCA)',
        'SUBIA (C/MARCA)',
        'SUSA (C/MARCA)',
        'TAUSA (C/MARCA)',
        'UTICA (C/MARCA)',
        'AGUA DE DIOS (C/MARCA)',
        'GIRARDOT (C/MARCA)',
        'CAJICA (C/MARCA)',
        'FACATATIVA (C/MARCA)',
        'MADRID (C/MARCA)',
        'SIBATE (C/MARCA)',
        'SOPO (C/MARCA)',
        'PARATEBUENO (C/MARCA)',
        'CARMEN DE CARUPA (C/MARCA)',
        'TENJO (C/MARCA)',
        'ZIPAQUIRA (C/MARCA)',
        'SOACHA (C/MARCA)',
        'BRICEÑO (C/MARCA)',
        'QUETAME (C/MARCA)',
        'ANOLAIMA (C/MARCA)',
        'ANAPOIMA (C/MARCA)',
        'ARBELAEZ (C/MARCA)',
        'BITUIMA (C/MARCA)',
        'BOJACA (C/MARCA)',
        'CABRERA (C/MARCA)',
        'CACHIPAY (C/MARCA)',
        'GAMA (C/MARCA)',
        'VENECIA -  (C/MARCA)',
        'GUAYABAL DE SIQUIMA (C/MARCA)',
        'CAQUEZA (C/MARCA)',
        'CHOACHI (C/MARCA)',
        'COGUA (C/MARCA)',
        'EL PEÑÓN (C/MARCA)',
        'GACHALA (C/MARCA)',
        'GRANADA (C/MARCA)',
        'GUADUAS (C/MARCA)',
        'GUATAQUI (C/MARCA)',
        'GUTIERREZ (C/MARCA)',
        'JUNIN (C/MARCA)',
        'MANTA (C/MARCA)',
        'NEMOCON (C/MARCA)',
        'LA FLORIDA (C/MARCA)',
        'CAPARRAPI (C/MARCA)',
        'LA UNION (C/MARCA)',
        'CHOCONTA (C/MARCA)',
        'EL ROSAL (C/MARCA)',
        'EL SISGA (C/MARCA)',
        'FOSCA (C/MARCA)',
        'GACHETA (C/MARCA)',
        'GUACHETA (C/MARCA)',
        'GUASCA (C/MARCA)',
        'GUAYABETAL (C/MARCA)',
        'JERUSALEN (C/MARCA)',
        'LA VICTORIA (C/MARCA)',
        'NARIÑO (C/MARCA)',
        'PASCA (C/MARCA)',
        'PUENTE DE PIEDRA (C/MARCA)',
        'PUERTO SALGAR (C/MARCA)',
        'PULI (C/MARCA)',
        'CHIPAQUE (C/MARCA)',
        'PUERTO BOGOTA (C/MARCA)',
        'MEDINA (C/MARCA)',
        'PACHO (C/MARCA)',
        'LA VEGA (C/MARCA)',
        'LENGUAZAQUE (C/MARCA)',
        'MACHETA (C/MARCA)',
        'NILO (C/MARCA)',
        'NIMAIMA (C/MARCA)',
        'NOCAIMA (C/MARCA)',
        'PAIME (C/MARCA)',
        'TUDELA (C/MARCA)',
        'VENECIA (C/MARCA)',
        'SANTANDERSITO (C/MARCA)',
        'CHAGUANI (C/MARCA)',
        'LA PEÑA (C/MARCA)',
        'SAN JUAN DE RIOSECO (C/MARCA)',
        'TOPAIPI (C/MARCA)',
        'QUIPILE (C/MARCA)',
        'TABIO (C/MARCA)',
        'TOCANCIPA (C/MARCA)',
        'CUCUNUBA (C/MARCA)',
        'EL COLEGIO MESITAS (C/MARCA)',
        'LA PALMA (C/MARCA)',
        'LA MESA (C/MARCA)',
        'EL TRIUNFO (C/MARCA)',
        'VIOTA (C/MARCA)',
        'FUNZA (C/MARCA)',
        'GACHANCIPA (C/MARCA)',
        'CHUSACA (C/MARCA)',
        'UNE (C/MARCA)',
        'CHIA (C/MARCA)',
        'SAN CAYETANO (C/MARCA)',
        'CHINAUTA (C/MARCA)',
        'SAN ANT DE TEQUEN (C/MARCA)',
        'TOBIA (C/MARCA)',
        'PANDI (C/MARCA)',
        'ALBAN (C/MARCA)',
        'LA GRAN VIA (C/MARCA)',
        'MAYA (C/MARCA)',
        'APULO (C/MARCA)',
        'SUPATA (C/MARCA)',
        'SAN FRANCISCO (C/MARCA)',
        'VILLETA (C/MARCA)',
        'YACOPI (C/MARCA)',
    ),
    '52' => array(
        'CUATRO ESQUINAS (NAR)',
        'POLICARPA (NAR)',
        'SAN JOSE DE ALBAN (NAR)',
        'CONTADERO (NAR)',
        'CAJAPI (NAR)',
        'IPIALES (NAR)',
        'ILES (NAR)',
        'CUMBITARA (NAR)',
        'IMUES (NAR)',
        'PUERRES (NAR)',
        'ESPRIELLA (NAR)',
        'TAMINANGO (NAR)',
        'FUNES (NAR)',
        'SOTOMAYOR (NAR)',
        'Providencia (Nar)',
        'GENOY (NAR)',
        'CUMBAL (NAR)',
        'EL TABLON DE GOMEZ (NAR)',
        'GUACHAVEZ SAN CRUZ (NAR)',
        'LA CRUZ (NAR)',
        'OBONUCO (NAR)',
        'RICAURTE (NAR)',
        'PINZON (NAR)',
        'ANCUYA (NAR)',
        'CATAMBUCO (NAR)',
        'CONSACA (NAR)',
        'CARLOSAMA  CUASPUD (NAR)',
        'EL ROSARIO (NAR)',
        'BERRUECOS ARBOLEDA (NAR)',
        'PUPIALES (NAR)',
        'EL REMOLINO (NAR)',
        'LA FLORIDA (NAR)',
        'CHACHAGUI (NAR)',
        'LA UNION (NAR)',
        'TANGUA (NAR)',
        'GENOVA (NAR)',
        'SAN LORENZO (NAR)',
        'SAPUYES (NAR)',
        'EL TAMBO (NAR)',
        'EL CHARCO (NAR)',
        'PASTO (NAR)',
        'EL PEÑOL (NAR)',
        'SAN PABLO (NAR)',
        'BELEN (NAR)',
        'CEBADAL (NAR)',
        'DAZA (NAR)',
        'EL ENCANO (NAR)',
        'JUNIN (NAR)',
        'LA LLANADA (NAR)',
        'TANGAREAL DEL MIRA (NAR)',
        'JOSE MARIA HERNANDEZ (NAR)',
        'LAS LAJAS (NAR)',
        'MOCONDINO (NAR)',
        'PILCUAN (NAR)',
        'YACUANQUER (NAR)',
        'LEIVA (NAR)',
        'SANDONA (NAR)',
        'ALDANA (NAR)',
        'ALTAQUER (NAR)',
        'BUESACO (NAR)',
        'GUACHUCAL (NAR)',
        'CANDELILLAS (NAR)',
        'CHUCUNES (NAR)',
        'SAMANIEGO (NAR)',
        'TUMACO (NAR)',
        'IMBILI (NAR)',
        'LLORENTE (NAR)',
        'GUALMATAN (NAR)',
        'OSPINA (NAR)',
        'LINARES (NAR)',
        'PIEDRAHANCHA (NAR)',
        'SAN PEDRO DE CARTAGO (NAR)',
        'POTOSI (NAR)',
        'SAN BERNARDO (NAR)',
        'TANGAREAL CARRETERA (NAR)',
        'CORDOBA (NAR)',
        'PROVIDENCIA (NAR)',
        'TUQUERRES (NAR)',
        'NARIÑO (NAR)',
        'EL ESPINO (NAR)',
        'EL DIVISO (NAR)',
        'GUAITARILLA (NAR)',
        'BARBACOAS (NAR)',
        'LA GUAYACANA (NAR)',
        'BUESAQUILLO (NAR)',
        'CABRERA (NAR)',
    ),
    '13' => array(
        'REGIDOR (BOL)',
        'CICUCO (BOL)',
        'TURBACO (BOL)',
        'BUENA SENA (BOL)',
        'SANTA ROSA (BOL)',
        'BARU (BOL)',
        'MONTECRISTO (BOL)',
        'SAN MARTIN DE LOBA (BOL)',
        'NOROSI (BOL)',
        'MAHATES (BOL)',
        'MORALES (BOL)',
        'JUAN ARIAS (BOL)',
        'MAGANGUE (BOL)',
        'MOMPOS (BOL)',
        'SAN JACINTO (BOL)',
        'SAN JUAN NEPOMUCENO (BOL)',
        'CANTAGALLO (BOL)',
        'RIO VIEJO (BOL)',
        'SIMITI (BOL)',
        'CLEMENCIA (BOL)',
        'ARENAL (BOL)',
        'CALAMAR (BOL)',
        'ARJONA (BOL)',
        'MARIA LA BAJA (BOL)',
        'SAN PABLO (BOL)',
        'SANTA ROSA DEL SUR (BOL)',
        'SANTA CATALINA (BOL)',
        'VILLANUEVA (BOL)',
        'CORDOBA (BOL)',
        'TALAIGUA NUEVO (BOL)',
        'CARTAGENA (BOL)',
        'BALLESTAS (BOL)',
        'PUERTO RICO - TIQUISIO (BOL)',
        'MARGARITA (BOL)',
        'SAN FERNANDO (BOL)',
        'Norosi (Bol.)',
        'PONTEZUELA (BOL)',
        'ACHI (BOL)',
        'PASACABALLOS (BOL)',
        'LA BOQUILLA (BOL)',
        'SANTA ANA (BOL)',
        'ZAMBRANO (BOL)',
        'LOMA DE ARENA (BOL)',
        'BAYUNCA (BOL)',
        'SOPLAVIENTO (BOL)',
        'TURBANA (BOL)',
        'BARRANCO DE LOBA (BOL)',
        'HATILLO DE LOBA (BOL)',
        'SAN ESTANISLAO (BOL)',
        'EL GUAMO (BOL)',
        'EL CARMEN DE BOLIVAR (BOL)',
        'GALERAZAMBA (BOL)',
    ),
    '17' => array(
        'VILLAMARIA (CDAS)',
        'LA MERCED (CDAS)',
        'MARMATO (CDAS)',
        'SAN FELIX (CDAS)',
        'VICTORIA (CDAS)',
        'LA DORADA (CDAS)',
        'NORCASIA (CDAS)',
        'SAN BARTOLOME (CDAS)',
        'SAN DANIEL (CDAS)',
        'VITERBO (CDAS)',
        'PALESTINA (CDAS)',
        'BOLIVIA (CDAS)',
        'ARAUCA (CDAS)',
        'SUPIA (CDAS)',
        'CASTILLA (CDAS)',
        'FLORENCIA (CDAS)',
        'PACORA (CDAS)',
        'PENSILVANIA (CDAS)',
        'SALAMINA (CDAS)',
        'SAMANA (CDAS)',
        'NEIRA (CDAS)',
        'ARBOLEDA (CDAS)',
        'BONAFONT (CDAS)',
        'SAMARIA (CDAS)',
        'LA FELISA (CDAS)',
        'AGUADAS (CDAS)',
        'GUARINOCITO (CDAS)',
        'MONTEBONITO (CDAS)',
        'ANSERMA (CDAS)',
        'ARANZAZU (CDAS)',
        'ARMA (CDAS)',
        'MARQUETALIA (CDAS)',
        'MARULANDA (CDAS)',
        'MANZANARES (CDAS)',
        'RIOSUCIO (CDAS)',
        'MANIZALES (CDAS)',
        'BELALCAZAR (CDAS)',
        'FILADELFIA (CDAS)',
        'CHINCHINA (CDAS)',
        'RISARALDA (CDAS)',
        'SAN JOSE (CDAS)',
        'SAN DIEGO (CDAS)',
    ),
    '23' => array(
        'SAHAGUN (CORD)',
        'SAN JOSE DE URE (CORD)',
        'COTORRA (CORD)',
        'AYAPEL (CORD)',
        'CERETE (CORD)',
        'CIENAGA DE ORO (CORD)',
        'LORICA (CORD)',
        'SAN CARLOS (CORD)',
        'LA YE (CORD)',
        'MOMIL (CORD)',
        'MONTELIBANO (CORD)',
        'PLANETA RICA (CORD)',
        'PUERTO ESCONDIDO (CORD)',
        'PURISIMA (CORD)',
        'SAN ANDRES DE SOTAVENTO (CORD)',
        'SAN ANTERO (CORD)',
        'SAN BERNARDO DEL VIENTO (CORD)',
        'SAN PELAYO (CORD)',
        'LA APARTADA (CORD)',
        'CHINU (CORD)',
        'BUENA VISTA (CORD)',
        'CHIMA (CORD)',
        'EL VIAJANO (CORD)',
        'COLOMBOY (CORD)',
        'VALENCIA (CORD)',
        'LOS CORDOBAS (CORD)',
        'SAN SEBASTIAN (CORD)',
        'MONTERIA (CORD)',
        'PUEBLO NUEVO (CORD)',
        'PUERTO LIBERTADOR (CORD)',
        'CARILLO (CORD)',
        'EL CARITO (CORD)',
        'EL VARAL (CORD)',
        'CANALETE (CORD)',
        'TIERRA ALTA (CORD)',
        'TUCHIN (CORD)',
        'VILLA FATIMA (CORD)',
        'MOÑITOS (CORD)',
    ),
    '08' => array(
        'CAMPECHE (ATL)',
        'GALAPA (ATL)',
        'BARANOA (ATL)',
        'SABANAGRANDE (ATL)',
        'SANTO TOMAS (ATL)',
        'REPELON (ATL)',
        'SANTA VERONICA (ATL)',
        'ARROYO DE PIEDRA (ATL)',
        'JUAN DE ACOSTA (ATL)',
        'POLONUEVO (ATL)',
        'SUAN (ATL)',
        'USIACURI (ATL)',
        'MOLINEROS (ATL)',
        'PLAYA MENDOZA (ATL)',
        'MALAMBO (ATL)',
        'PUERTO GIRALDO (ATL)',
        'LA PEÑA (ATL)',
        'TUBARA (ATL)',
        'SOLEDAD (ATL)',
        'PONEDERA (ATL)',
        'PUERTO COLOMBIA (ATL)',
        'BARRANQUILLA (ATL)',
        'JUAN MINA (ATL)',
        'LURUACO (ATL)',
        'CAMPO DE LA CRUZ (ATL)',
        'CANDELARIA (ATL)',
        'SANTA LUCIA (ATL)',
        'ISABEL LOPEZ (ATL)',
        'MANATI (ATL)',
        'PALMAR DE VARELA (ATL)',
        'PIOJO (ATL)',
        'SABANALARGA (ATL)',
        'SALGAR (ATL)',
    ),
    '19' => array(
        'LOPEZ DE MICAY (CAU)',
        'MERCADERES (CAU)',
        'CALOTO (CAU)',
        'PUERTO TEJADA (CAU)',
        'EL PATIA (CAU)',
        'EL NARANJAL (CAU)',
        'FLORENCIA (CAU)',
        'GUACHENE (CAU)',
        'INZA (CAU)',
        'JAMBALO (CAU)',
        'PURACE (CAU)',
        'SAN SEBASTIAN (CAU)',
        'SANTANDER DE QUILICHAO (CAU)',
        'SUAREZ (CAU)',
        'TIMBIO (CAU)',
        'TORIBIO (CAU)',
        'SILVIA (CAU)',
        'TIMBA (CAU)',
        'PIENDAMO (CAU)',
        'TIMBIQUI (CAU)',
        'PIEDRASENTADA (CAU)',
        'CAJIBIO (CAU)',
        'EL BORDO (CAU)',
        'EL ESTRECHO (CAU)',
        'PAISPAMBA SOTARA (CAU)',
        'PADILLA (CAU)',
        'ALMAGUER (CAU)',
        'PESCADOR (CAU)',
        'CALDONO (CAU)',
        'CORINTO (CAU)',
        'ARGELIA (CAU)',
        'POPAYAN (CAU)',
        'BUENOS AIRES (CAU)',
        'SAN JOSE (CAU)',
        'BELALCAZAR PAEZ (CAU)',
        'COCONUCO (CAU)',
        'MONDOMO (CAU)',
        'BALBOA (CAU)',
        'GALINDEZ (CAU)',
        'LA SIERRA (CAU)',
        'MIRANDA (CAU)',
        'MORALES (CAU)',
        'ORTIGAL (CAU)',
        'TUNIA (CAU)',
        'MOJARRAS (CAU)',
        'LA VEGA (CAU)',
        'SAN LORENZO (CAU)',
        'BOLIVAR (CAU)',
        'ROSAS (CAU)',
        'EL TAMBO (CAU)',
        'GUAPI (CAU)',
        'VILLA RICA (CAU)',
        'TOTORO (CAU)',
    ),
    '47' => array(
        'CHIVOLO (MG/LENA)',
        'CIENAGA (MG/LENA)',
        'CONCORDIA (MG/LENA)',
        'ALGARROBO (MG/LENA)',
        'PLATO (MG/LENA)',
        'REMOLINO (MG/LENA)',
        'SITIO NUEVO (MG/LENA)',
        'MEDIA LUNA (MG/LENA)',
        'EL RETEN (MG/LENA)',
        'PUEBLONUEVO (MG/LENA)',
        'SANTA MARTA (MG/LENA)',
        'EL DIFICIL (MG/LENA)',
        'GUAMAL (MG/LENA)',
        'FUNDACION (MG/LENA)',
        'PUEBLOVIEJO (MG/LENA)',
        'SAN FERNANDO (MG/LENA)',
        'SABANAS DE SAN ANGEL (MG/LENA)',
        'SAN ZENON (MG/LENA)',
        'PALERMO (MG/LENA)',
        'ARACATACA (MG/LENA)',
        'EL PIÑON (MG/LENA)',
        'TUCURINCA (MG/LENA)',
        'SALAMINA (MG/LENA)',
        'TAGANGA (MG/LENA)',
        'PIJIÑO DEL CARMEN (MG/LENA)',
        'GUACAMAYAL (MG/LENA)',
        'EL BANCO (MG/LENA)',
        'SAN SEBAST DE BUENAVI (MG/LENA)',
        'CERRO SAN ANTONIO (MG/LENA)',
        'TENERIFE (MG/LENA)',
        'PIVIJAY (MG/LENA)',
        'GAIRA (MG/LENA)',
        'LA GRAN VIA (MG/LENA)',
        'RIOFRIO (MG/LENA)',
        'PRADO SEVILLA (MG/LENA)',
        'NUEVA GRANADA (MG/LENA)',
        'ORIHUECA (MG/LENA)',
        'SANTA BARBARA DE PINTO (MG/LENA)',
        'GUAIMARO (MG/LENA)',
        'PEDRAZA (MG/LENA)',
        'SANTA ANA (MG/LENA)',
    ),
    '68' => array(
        'LEBRIJA (STDER)',
        'BUCARAMANGA (STDER)',
        'GALAN (STDER)',
        'SUAITA (STDER)',
        'BOLIVAR (STDER)',
        'GAMBITA (STDER)',
        'CERRITO (STDER)',
        'SAN JOAQUIN (STDER)',
        'ONZAGA (STDER)',
        'GIRON (STDER)',
        'SAN ANDRES (STDER)',
        'BARBOSA (STDER)',
        'EL PLAYON (STDER)',
        'MATANZA (STDER)',
        'CONTRATACION (STDER)',
        'CURITI (STDER)',
        'CONCEPCION (STDER)',
        'BARICHARA (STDER)',
        'SAN VICENTE DE CHUCURI (STDER)',
        'SOCORRO (STDER)',
        'PUERTO OLAYA (STDER)',
        'EL CENTRO (STDER)',
        'PUERTO ARAUJO (STDER)',
        'LANDAZURI (STDER)',
        'VELEZ (STDER)',
        'CIMITARRA (STDER)',
        'SABANA DE TORRES (STDER)',
        'OIBA (STDER)',
        'RIONEGRO (STDER)',
        'LA PAZ (STDER)',
        'SAN JOSE DE MIRANDA (STDER)',
        'MALAGA (STDER)',
        'PUERTO PARRA (STDER)',
        'ACAPULCO (STDER)',
        'VALLE DE SAN JOSE (STDER)',
        'VILLANUEVA (STDER)',
        'PINCHOTE (STDER)',
        'PESCADERO (STDER)',
        'BARRANCABERMEJA (STDER)',
        'GUACA (STDER)',
        'GUEPSA (STDER)',
        'FLORIAN (STDER)',
        'AGUADA (STDER)',
        'OLIVAL (STDER)',
        'PUERTO WILCHES (STDER)',
        'CHIPATA (STDER)',
        'PUENTE NACIONAL (STDER)',
        'EL CARMEN DE CHUCURI (STDER)',
        'FLORIDABLANCA (STDER)',
        'SUCRE (STDER)',
        'GUADALUPE (STDER)',
        'ZAPATOCA (STDER)',
        'MOGOTES (STDER)',
        'MOLAGAVITA (STDER)',
        'ENCISO (STDER)',
        'ARATOCA (STDER)',
        'JESUS MARIA (STDER)',
        'GUAVATA (STDER)',
        'CAPITANEJO (STDER)',
        'LA BELLEZA (STDER)',
        'LA GRANJA (STDER)',
        'PARAMO (STDER)',
        'SIMACOTA (STDER)',
        'SAN GIL (STDER)',
        'CHARALA (STDER)',
        'VADO REAL (STDER)',
        'EL PEÑON (STDER)',
        'PIEDECUESTA (STDER)',
        'SAN BENITO (STDER)',
        'SANTA HELENA DEL OPON (STDER)',
    ),
    '73' => array(
        'PADUA (TOL)',
        'PALOCABILDO (TOL)',
        'CONVENIO (TOL)',
        'CASABIANCA (TOL)',
        'FALAN (TOL)',
        'FRESNO (TOL)',
        'BOQUERON (TOL)',
        'CALDAS VIEJO (TOL)',
        'CASTILLA (TOL)',
        'PRADO (TOL)',
        'LA PALMITA (TOL)',
        'ALPUJARRA (TOL)',
        'MURILLO (TOL)',
        'RIOBLANCO (TOL)',
        'SAN LUIS (TOL)',
        'RONCESVALLES (TOL)',
        'ATACO (TOL)',
        'VALLE DE SAN JUAN (TOL)',
        'SAN FELIPE (TOL)',
        'ORTEGA (TOL)',
        'PASTALES VIEJO (TOL)',
        'CHENCHE ASOLEADO (TOL)',
        'EL TABLAZO (TOL)',
        'GAITANIA (TOL)',
        'CUNDAY (TOL)',
        'JUNÍN (TOL)',
        'LA ARADA (TOL)',
        'LA CHAMBA (TOL)',
        'OLAYA HERRERA (TOL)',
        'SAN ANTONIO (TOL)',
        'PLAYARRICA (TOL)',
        'EL LIMON (TOL)',
        'SANTA TERESA (TOL)',
        'ALVARADO (TOL)',
        'ARMERO GUAYABAL (TOL)',
        'COYAIMA (TOL)',
        'PAYANDE (TOL)',
        'COELLO - COCORA (TOL)',
        'DOIMA (TOL)',
        'VELU (TOL)',
        'CARMEN DE APICALA (TOL)',
        'BUENOS AIRES (TOL)',
        'JUNTAS (TOL)',
        'ESPINAL (TOL)',
        'CHICORAL (TOL)',
        'MELGAR (TOL)',
        'GUALANDAY (TOL)',
        'PLANADAS (TOL)',
        'PURIFICACION (TOL)',
        'NATAGAIMA (TOL)',
        'SANTIAGO PEREZ (TOL)',
        'LA SIERRA (TOL)',
        'ANZOATEGUI (TOL)',
        'IBAGUE (TOL)',
        'FLANDES (TOL)',
        'HERBEO (TOL)',
        'VILLARESTREPO (TOL)',
        'EL TOTUMO (TOL)',
        'CAJAMARCA (TOL)',
        'CHAPARRAL (TOL)',
        'GUAMO (TOL)',
        'HONDA (TOL)',
        'ICONONZO (TOL)',
        'LERIDA (TOL)',
        'VENADILLO (TOL)',
        'LIBANO (TOL)',
        'MARIQUITA (TOL)',
        'PASTALES NUEVO (TOL)',
        'SALDANA (TOL)',
        'SANTA ISABEL (TOL)',
        'VILLA RICA (TOL)',
        'COELLO (TOL)',
        'DOLORES (TOL)',
        'HERRERA (TOL)',
        'PIEDRAS (TOL)',
        'SUAREZ (TOL)',
        'VILLAHERMOSA (TOL)',
        'AMBALEMA (TOL)',
        'ROVIRA (TOL)',
        'TRES ESQUINAS (TOL)',
    ),
    '66' => array(
        'GUATICA (RS)',
        'BELEN DE UMBRIA (RS)',
        'SANTA ROSA DE CABAL (RS)',
        'IRRA (RS)',
        'APIA (RS)',
        'MARSELLA (RS)',
        'QUINCHIA (RS)',
        'MISTRATO (RS)',
        'PEREIRA (RS)',
        'SAN CLEMENTE (RS)',
        'BALBOA (RS)',
        'PUEBLO RICO (RS)',
        'LA VIRGINIA (RS)',
        'DOSQUEBRADAS (RS)',
        'LA CELIA (RS)',
        'SANTUARIO (RS)',
    ),
    '41' => array(
        'BARAYA (HLA)',
        'VILLA VIEJA (HLA)',
        'SUAZA (HLA)',
        'NATAGA (HLA)',
        'VEGALARGA (HLA)',
        'SANTA MARIA (HLA)',
        'PALERMO (HLA)',
        'BELEN (HLA)',
        'PALESTINA (HLA)',
        'ALTAMIRA (HLA)',
        'YAGUARA (HLA)',
        'PAICOL (HLA)',
        'OPORAPA (HLA)',
        'SAN AGUSTIN (HLA)',
        'GUADALUPE (HLA)',
        'AGRADO (HLA)',
        'SAN ADOLFO (HLA)',
        'GIGANTE (HLA)',
        'TELLO (HLA)',
        'PITALITO (HLA)',
        'GARZON (HLA)',
        'TARQUI (HLA)',
        'TIMANA (HLA)',
        'LA PLATA (HLA)',
        'TESALIA (HLA)',
        'ARGENTINA (HLA)',
        'RIVERA (HLA)',
        'AIPE (HLA)',
        'BRUSELAS (HLA)',
        'ALGECIRAS (HLA)',
        'COLOMBIA (HLA)',
        'SALADO BLANCO (HLA)',
        'SAN JOSE DE ISNOS (HLA)',
        'PITAL (HLA)',
        'NEIVA (HLA)',
        'ACEVEDO (HLA)',
        'HOBO (HLA)',
        'IQUIRA (HLA)',
        'TERUEL (HLA)',
        'CAMPOALEGRE (HLA)',
    ),
    '70' => array(
        'TOLU (SUCRE)',
        'SAN MARCOS (SUCRE)',
        'SAN BENITO ABAD (SUCRE)',
        'GALERAS (SUCRE)',
        'OVEJAS (SUCRE)',
        'SAN ONOFRE (SUCRE)',
        'MORROA (SUCRE)',
        'GUARANDA (SUCRE)',
        'SAN PEDRO (SUCRE)',
        'COROZAL (SUCRE)',
        'SINCELEJO (SUCRE)',
        'SINCE (SUCRE)',
        'MAJAGUAL (SUCRE)',
        'SUCRE (SUCRE)',
        'TOLU VIEJO (SUCRE)',
        'SAMPUES (SUCRE)',
        'LOS PALMITOS (SUCRE)',
        'LA UNION (SUCRE)',
        'CAIMITO (SUCRE)',
        'COVEÑAS (SUCRE)',
    ),
    '54' => array(
        'LA PLAYA (N/STDER)',
        'EL CARMEN (N/STDER)',
        'CUCUTA (N/STDER)',
        'CACHIRA (N/STDER)',
        'LOURDES (N/STDER)',
        'RAGONVALIA (N/STDER)',
        'ABREGO (N/STDER)',
        'PAMPLONA (N/STDER)',
        'SAN CAYETANO (N/STDER)',
        'CONVENCION (N/STDER)',
        'CHINACOTA (N/STDER)',
        'SANTIAGO (N/STDER)',
        'SARDINATA (N/STDER)',
        'VILLA CARO (N/STDER)',
        'BOCHALEMA (N/STDER)',
        'CACOTA (N/STDER)',
        'BUCARASICA (N/STDER)',
        'DURANIA (N/STDER)',
        'EL ZULIA (N/STDER)',
        'LABATECA (N/STDER)',
        'CHITAGA (N/STDER)',
        'CUCUTILLA (N/STDER)',
        'MUTISCUA (N/STDER)',
        'PAMPLONITA (N/STDER)',
        'SALAZAR (N/STDER)',
        'TEORAMA (N/STDER)',
        'LA ESPERANZA (N/STDER)',
        'VILLA DEL ROSARIO (N/STDER)',
        'SILOS (N/STDER)',
        'TOLEDO (N/STDER)',
        'SAN BERNARDO (N/STDER)',
        'ARBOLEDAS (N/STDER)',
        'LOS PATIOS (N/STDER)',
        'TIBU (N/STDER)',
        'OCAÑA (N/STDER)',
        'HERRAN (N/STDER)',
        'SAN CALIXTO (N/STDER)',
        'GRAMALOTE (N/STDER)',
        'HACARI (N/STDER)',
        'PUERTO SANTANDER (N/STDER)',
    ),
    '86' => array(
        'PUERTO GUZMAN (P/MAYO)',
        'ORITO (P/MAYO)',
        'EL TIGRE (P/MAYO)',
        'MOCOA (P/MAYO)',
        'LA HORMIGA - VALLE GUAMUEZ (P/MAYO)',
        'COLON (P/MAYO)',
        'SANTANA (P/MAYO)',
        'PUERTO CAICEDO (P/MAYO)',
        'PUERTO ASIS (P/MAYO)',
        'PUERTO UMBRIA (P/MAYO)',
        'SIBUNDOY (P/MAYO)',
        'VILLAGARZON (P/MAYO)',
        'SAN FRANCISCO (P/MAYO)',
        'LA DORADA SAN MIGUEL (P/MAYO)',
        'SANTIAGO (P/MAYO)',
        'PUERTO LEGUIZAMO (P/MAYO)',
    ),
    '20' => array(
        'SAN DIEGO (CES)',
        'LA PAZ (CES)',
        'CODAZZI- AGUSTIN (CES)',
        'SAN MARTIN (CES)',
        'ARJONA (CES)',
        'TAMALAMEQUE (CES)',
        'EL PASO (CES)',
        'MANAURE BALCON DEL CESAR (CES)',
        'CHIMICHAGUA (CES)',
        'CARACOLICITO (CES)',
        'LA LOMA (CES)',
        'ASTREA (CES)',
        'PUEBLO BELLO (CES)',
        'GAMARRA (CES)',
        'LA GLORIA (CES)',
        'PAILITAS (CES)',
        'AYACUCHO (CES)',
        'RIO DE ORO (CES)',
        'SAN ALBERTO (CES)',
        'PELAYA (CES)',
        'AGUACHICA (CES)',
        'LA JAGUA DE IBIRICO (CES)',
        'EL COPEY (CES)',
        'CHIRIGUANA (CES)',
        'CURUMANI (CES)',
        'RINCON HONDO (CES)',
        'SAN ROQUE (CES)',
        'BECERRIL (CES)',
        'BOSCONIA (CES)',
        'VALLEDUPAR (CES)',
        'GONZALEZ (CES)',
    ),
    '50' => array(
        'LEJANIAS (META)',
        'LA MACARENA (META)',
        'VILLAVICENCIO (META)',
        'CUBARRAL SAN LUIS (META)',
        'FUENTE DE ORO (META)',
        'GRANADA (META)',
        'SAN MARTIN (META)',
        'PUERTO RICO (META)',
        'URIBE (META)',
        'ACACIAS (META)',
        'PUERTO GAITAN (META)',
        'VISTA HERMOSA (META)',
        'BARRANCA DE UPIA (META)',
        'PACHAQUIARO (META)',
        'CASTILLA LA NUEVA (META)',
        'RESTREPO (META)',
        'PUERTO LLERAS (META)',
        'GUAMAL (META)',
        'SAN JUAN DE ARAMA (META)',
        'CUMARAL (META)',
        'PUERTO LOPEZ (META)',
        'APIAY (META)',
        'PUERTO CONCORDIA (META)',
    ),
    '88' => array(
        'PROVIDENCIA (S/ANDRES)',
        'SANTA CATALINA (S/ANDRES)',
        'SAN ANDRES ISLA (S/ANDRES)',
    ),
    '85' => array(
        'PORE (C/NARE)',
        'SABANALARGA (C/NARE)',
        'AGUACLARA (C/NARE)',
        'CUSIANA POZO (C/NARE)',
        'VILLANUEVA (C/NARE)',
        'MONTERREY (C/NARE)',
        'SAN LUIS DE PALENQUE (C/NARE)',
        'NUNCHIA (C/NARE)',
        'OROCUE (C/NARE)',
        'AGUAZUL (C/NARE)',
        'LA CHAPARRERA (C/NARE)',
        'ARAGUANEY (C/NARE)',
        'VILLACAROLA (C/NARE)',
        'TRINIDAD (C/NARE)',
        'TAURAMENA (C/NARE)',
        'PAZ DE ARIPORO (C/NARE)',
        'MANI (C/NARE)',
        'HATO COROZAL (C/NARE)',
        'YOPAL (C/NARE)',
    ),
    '97' => array(
        'MITU (V/PES)',
    ),
    '94' => array(
        'INIRIDA (GUAI)',
    ),
    '81' => array(
        'PUERTO RONDON (ARAU)',
        'SARAVENA (ARAU)',
        'FORTUL (ARAU)',
        'LA PESQUERA (ARAU)',
        'CRAVO NORTE (ARAU)',
        'PUERTO NARIÑO (ARAU)',
        'ARAUQUITA (ARAU)',
        'LA ESMERALDA (ARAU)',
        'TAME (ARAU)',
        'ARAUCA (ARAU)',
    ),
    '44' => array(
        'BUENAVISTA (GUAJ)',
        'ALBANIA (GUAJ)',
        'BARRANCAS (GUAJ)',
        'VILLANUEVA (GUAJ)',
        'MANAURE (GUAJ)',
        'MAICAO (GUAJ)',
        'URIBIA (GUAJ)',
        'SAN JUAN DEL CESAR (GUAJ)',
        'FONSECA (GUAJ)',
        'URUMITA (GUAJ)',
        'EL MOLINO (GUAJ)',
        'LA JAGUA DEL PILAR (GUAJ)',
        'MINGUEO (GUAJ)',
        'RIOHACHA (GUAJ)',
        'DISTRACCION (GUAJ)',
        'HATO NUEVO (GUAJ)',
    ),
    '11' => array(
        'BOGOTA (C/MARCA)',
    ),
    '91' => array(
        'LETICIA (AMAZ)',
    )
);
